fans:
    run: false
follow:
    run: false
data:
    run: false

logging:
    config: classpath:logback-spring.xml

server:
  context-path: /

spring:
    profiles:
        active: dev
    freemarker:
        cache: false
        suffix: .ftl
        request-context-attribute: request
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
    http:
      multipart:
        max-file-size: 15Mb
        max-request-size: 20Mb