logging:
    level:
        root: INFO
        #com.cpic.community: DEBUG
    config: classpath:logback-spring.xml

server:
  context-path: /yunsearch

spring:
    profiles:
        active: prod
    freemarker:
        cache: false
        suffix: .ftl
        request-context-attribute: request
    jpa:
      hibernate:
        ddl-auto: update
    http:
      multipart:
        max-file-size: 15Mb
        max-request-size: 20Mb